repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
- repo: https://github.com/crate-ci/typos
  rev: v1.32.0
  hooks:
    - id: typos
- repo: local
  hooks:
    - id: nixfmt
      name: nixfmt
      language: system
      entry: nix run github:NixOS/nixfmt
      files: \.nix$
