{
  inputs,
  config,
  ...
}: let
  inherit (config.hostCfg) username;
in {
  imports = [
    inputs.nix-homebrew.darwinModules.nix-homebrew
  ];

  # NOTE : nix-darwin can integrate with homebrew iff it is installed. Following
  # section handles that.
  nix-homebrew = {
    enable = true;
    user = username;
  };

  homebrew = {
    enable = true;
    #NOTE: Following will remove all formulae not listed in the Brewfile generated by nix-darwin
    # Set to keep nix and brew in sync.
    onActivation.cleanup = "uninstall";
  };
}
