{
  config,
  hostCfg,
  inputs,
  ...
}:
let
  inherit (hostCfg) username;
in
{
  imports = [
    inputs.nix-homebrew.darwinModules.nix-homebrew
  ];

  # NOTE : nix-darwin can integrate with homebrew iff it is installed. Following
  # section handles that.
  nix-homebrew = {
    enable = true;
    user = username;
    taps = {
      "homebrew/homebrew-core" = inputs.homebrew-core;
      "homebrew/homebrew-cask" = inputs.homebrew-cask;
    };
    mutableTaps = false;
  };

  homebrew = {
    enable = true;
    #NOTE: Following will remove all formulae not listed in the Brewfile generated by nix-darwin
    # Set to keep nix and brew in sync.
    onActivation.cleanup = "uninstall";
    taps = builtins.attrNames config.nix-homebrew.taps;
  };
}
