services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${BAZARR_PORT}:6767
      - ${RADARR_PORT}:7878
      - ${SONARR_PORT}:8989
      - ${FLARESOLVERR_PORT}:8191
      - ${PROWLARR_PORT}:9696
      - ${SABNZBD_PORT}:8080
      - ${QBITTORRENT_PORT}:8082
      - "6881:6881"
      - 6881:6881/udp
    environment:
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      OWNED_ONLY: ${OWNED_ONLY}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
