services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${ENTERTAINMENT_DIR}/media:/data/media
    network_mode: service:gluetun
    devices:
      - /dev/dri:/dev/dri
