services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SPEEDTEST_TRACKER_PORT1}:80
      - ${SPEEDTEST_TRACKER_PORT2}:443
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      APP_KEY: ${SPEEDTEST_TRACKER_APP_KEY}
      SPEEDTEST_SCHEDULE: 18 */2 * * *
    volumes:
      - ${CONFIG_DIR}/speedtest-tracker:/config
